[package]
name = "tsp-rust"
version = "0.1.0"
authors = ["Michael Gilbert <gilbertm@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
rand = "0.8.0"

[profile.release]
opt-level = 3
